version: '3.8'

services:
  backend:
    build: .
    container_name: hashbase-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
      - meilisearch

  db:
    image: postgres:15
    container_name: hashbase-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: hashbase-meilisearch
    environment:
      MEILI_NO_ANALYTICS: 'true'
    ports:
      - '7700:7700'

volumes:
  pgdata:
